config/routes.rb
require 'sidekiq/web'

Sidekiq::Web.use Rack::Auth::Basic do |username, password|
  username == ENV['SIDEKIQ_USERNAME'] && password == ENV['SIDEKIQ_PASSWORD']
end if Rails.env.production?

Rails.application.routes.draw do
  root to: 'home#index'

  resources :search_analytics
  resources :search_boxes
  resources :home, only: [:index, :update]

  mount Sidekiq::Web => '/sidekiq'
end

app/models/search_analytic.rb
class SearchAnalytic
  include Mongoid::Document
  field :text, type: String
  field :count, type: Integer
end

app/models/search_box.rb
class SearchBox
  include Mongoid::Document
  include Mongoid::Timestamps::Created
  field :text, type: String
  field :ip, type: String
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def update
  end
end

app/controllers/search_analytics_controller.rb
class SearchAnalyticsController < ApplicationController
  before_action :set_search_analytic, only: [:show, :edit, :update, :destroy]

  # GET /search_analytics
  def index
    @search_analytics = SearchAnalytic.all
  end

  # GET /search_analytics/1
  def show
  end

  # GET /search_analytics/new
  def new
    @search_analytic = SearchAnalytic.new
  end

  # GET /search_analytics/1/edit
  def edit
  end

  # POST /search_analytics
  def create
    @search_analytic = SearchAnalytic.new(search_analytic_params)

    if @search_analytic.save
      redirect_to @search_analytic, notice: 'Search analytic was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /search_analytics/1
  def update
    if @search_analytic.update(search_analytic_params)
      redirect_to @search_analytic, notice: 'Search analytic was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /search_analytics/1
  def destroy
    @search_analytic.destroy
    redirect_to search_analytics_url, notice: 'Search analytic was successfully destroyed.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_search_analytic
    @search_analytic = SearchAnalytic.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def search_analytic_params
    params.require(:search_analytic).permit(:text, :count)
  end
end

app/controllers/search_boxes_controller.rb
class SearchBoxesController < ApplicationController
  before_action :set_search_box, only: [:show, :edit, :update, :destroy]

  # GET /search_boxes
  # GET /search_boxes.json
  def index
    @search_boxes = SearchBox.all
    respond_to do |format|
      format.html
      format.json { render json: @search_boxes }
    end
  end

  # GET /search_boxes/1
  # GET /search_boxes/1.json
  def show
  end

  # GET /search_boxes/new
  def new
    @search_box = SearchBox.new
  end

  # GET /search_boxes/1/edit
  def edit
  end

  # POST /search_boxes
  # POST /search_boxes.json
  def create
    @search_box = SearchBox.new(search_box_params)

    respond_to do |format|
      if @search_box.save
        format.html do
          redirect_to @search_box, notice: notice_message('created')
        end
        format.json { render :show, status: :created, location: @search_box }
      else
        format.html { render :new }
        format.json do
          render json: @search_box.errors, status: :unprocessable_entity
        end
      end
    end
  end

  # PATCH/PUT /search_boxes/1
  # PATCH/PUT /search_boxes/1.json
  def update
    respond_to do |format|
      if @search_box.update(search_box_params)
        format.html do
          redirect_to @search_box, notice: notice_message('updated')
        end
        format.json { render :show, status: :ok, location: @search_box }
      else
        format.html { render :edit }
        format.json do
          render json: @search_box.errors, status: :unprocessable_entity
        end
      end
    end
  end

  # DELETE /search_boxes/1
  # DELETE /search_boxes/1.json
  def destroy
    @search_box.destroy
    respond_to do |format|
      format.html do
        redirect_to search_boxes_url, notice: notice_message('destroyed')
      end
      format.json { head :no_content }
    end
  end

  private

  # Generate notice message
  def notice_message(action)
    'Search box was successfully #{action}.'
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_search_box
    @search_box = SearchBox.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list
  # through.
  def search_box_params
    params.require(:search_box).permit(:text, :ip)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/search_analytics_helper.rb
module SearchAnalyticsHelper
end

app/helpers/search_boxes_helper.rb
module SearchBoxesHelper
end

app/views/home/index.html.erb
<h1>Search</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HelpSearch</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Help Search</a>
    </div>
  </div>
</div>

<%= yield %>

</body>
</html>

app/views/search_analytics/_form.html.erb
<%= form_for(@search_analytic) do |f| %>
  <% if @search_analytic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@search_analytic.errors.count, "error") %> prohibited this search_analytic from being saved:</h2>

      <ul>
      <% @search_analytic.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :text %><br>
    <%= f.text_field :text %>
  </div>
  <div class="field">
    <%= f.label :count %><br>
    <%= f.number_field :count %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/search_analytics/edit.html.erb
<h1>Editing Search Analytic</h1>

<%= render 'form' %>

<%= link_to 'Show', @search_analytic %> |
<%= link_to 'Back', search_analytics_path %>

app/views/search_analytics/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Search Analytics</h1>

<table>
  <thead>
    <tr>
      <th>Text</th>
      <th>Count</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @search_analytics.each do |search_analytic| %>
      <tr>
        <td><%= search_analytic.text %></td>
        <td><%= search_analytic.count %></td>
        <td><%= link_to 'Show', search_analytic %></td>
        <td><%= link_to 'Edit', edit_search_analytic_path(search_analytic) %></td>
        <td><%= link_to 'Destroy', search_analytic, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Search analytic', new_search_analytic_path %>

app/views/search_analytics/new.html.erb
<h1>New Search Analytic</h1>

<%= render 'form' %>

<%= link_to 'Back', search_analytics_path %>

app/views/search_analytics/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Text:</strong>
  <%= @search_analytic.text %>
</p>

<p>
  <strong>Count:</strong>
  <%= @search_analytic.count %>
</p>

<%= link_to 'Edit', edit_search_analytic_path(@search_analytic) %> |
<%= link_to 'Back', search_analytics_path %>

app/views/search_boxes/_form.html.erb
<%= form_for(@search_box) do |f| %>
  <% if @search_box.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@search_box.errors.count, "error") %> prohibited this search_box from being saved:</h2>

      <ul>
      <% @search_box.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :text %><br>
    <%= f.text_field :text %>
  </div>
  <div class="field">
    <%= f.label :ip %><br>
    <%= f.text_field :ip %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/search_boxes/edit.html.erb
<h1>Editing Search Box</h1>

<%= render 'form' %>

<%= link_to 'Show', @search_box %> |
<%= link_to 'Back', search_boxes_path %>

app/views/search_boxes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Search Boxes</h1>

<table>
  <thead>
    <tr>
      <th>Text</th>
      <th>Ip</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @search_boxes.each do |search_box| %>
      <tr>
        <td><%= search_box.text %></td>
        <td><%= search_box.ip %></td>
        <td><%= link_to 'Show', search_box %></td>
        <td><%= link_to 'Edit', edit_search_box_path(search_box) %></td>
        <td><%= link_to 'Destroy', search_box, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Search box', new_search_box_path %>

app/views/search_boxes/new.html.erb
<h1>New Search Box</h1>

<%= render 'form' %>

<%= link_to 'Back', search_boxes_path %>

app/views/search_boxes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Text:</strong>
  <%= @search_box.text %>
</p>

<p>
  <strong>Ip:</strong>
  <%= @search_box.ip %>
</p>

<%= link_to 'Edit', edit_search_box_path(@search_box) %> |
<%= link_to 'Back', search_boxes_path %>